export const ADD_MOVIES = "ADD_MOVIES";
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_SELECTED_MOVIE_REQUEST = "FETCH_SELECTED_MOVIE_REQUEST";
export const REMOVE_SELECTED_MOVIE = "REMOVE_SELECTED_MOVIE";
export const FETCH_ACTORS_REQUEST = "FETCH_ACTORS_REQUEST";