export const ADD_MOVIES = "ADD_MOVIES";
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_SELECTED_MOVIE_REQUEST = "FETCH_SELECTED_MOVIE_REQUEST";
export const REMOVE_SELECTED_MOVIE = "REMOVE_SELECTED_MOVIE";
export const FETCH_ACTORS_REQUEST = "FETCH_ACTORS_REQUEST";

export const FETCH_SEARCH_REQUEST = "FETCH_SEARCH_REQUEST";
export const CLEAR_SEARCH_DATA = "CLEAR_SEARCH_DATA";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";

export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";

export const ADD_WATCHLIST_MOVIE = "ADD_WATCHLIST_MOVIE";
export const REMOVE_WATCHLIST_MOVIE = "REMOVE_WATCHLIST_MOVIE";
